webtalk_init -webtalk_dir C:/Users/Galal/Desktop/PPI/PCI_ARBITER/project_arbiter/project_arbiter.sim/sim_1/behav/xsim/xsim.dir/ARBITER_6_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec 27 12:29:40 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a8b159c2-3960-434e-85c7-cf7da5d8a39a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a238405f414e42509fbb8b208b8e2c37" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "103" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5440_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3415247887 -regid "" -xml C:/Users/Galal/Desktop/PPI/PCI_ARBITER/project_arbiter/project_arbiter.sim/sim_1/behav/xsim/xsim.dir/ARBITER_6_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Galal/Desktop/PPI/PCI_ARBITER/project_arbiter/project_arbiter.sim/sim_1/behav/xsim/xsim.dir/ARBITER_6_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Galal/Desktop/PPI/PCI_ARBITER/project_arbiter/project_arbiter.sim/sim_1/behav/xsim/xsim.dir/ARBITER_6_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
